#!/usr/bin/env bash

session="$(
  tmux list-sessions -F "#{session_name}" |
    fzf \
      --prompt="session> " \
      --preview 'tmux list-windows -t {} -F "#{window_index}: #{window_name}"'
)"

[ -n "$session" ] && tmux switch-client -t "$session"
