#!/bin/bash

font_name="$1"

if [[ -n "$font_name" && "$font_name" != "CNCLD" ]]; then
  if fc-list | grep -iq "$font_name"; then
    if [[ -f ~/.config/alacritty/alacritty.toml ]]; then
      sed -i "s/family = \".*\"/family = \"$font_name\"/g" ~/.config/alacritty/alacritty.toml
    fi

    if [[ -f ~/.config/wezterm/wezterm.lua ]]; then
      sed -i "s/config.font = wezterm.font(\".*\")/config.font = wezterm.font(\"$font_name\")/g" ~/.config/wezterm/wezterm.lua
      pkill -SIGUSR1 wezterm
    fi

    sed -i "s/font-family: .*/font-family: '$font_name';/g" ~/.config/waybar/style.css
    sed -i "s/font-family: .*/font-family: '$font_name';/g" ~/.config/swayosd/style.css
    xmlstarlet ed -L \
      -u '//match[@target="pattern"][test/string="monospace"]/edit[@name="family"]/string' \
      -v "$font_name" \
      ~/.config/fontconfig/fonts.conf

    restart-waybar
    restart-swayosd
  else
    echo "Font '$font_name' not found."
    exit 1
  fi
else
  echo "Usage: font-set <font-name>"
fi
