$browser = launch-browser

bindd = SUPER, RETURN, Terminal, exec, launch-terminal
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, T, Activity, exec, launch-with-terminal btop
bindd = SUPER, D, Docker, exec, launch-with-terminal lazydocker
bindd = SUPER, S, Wiremix, exec, launch-with-terminal wiremix

bindd = ALT, P, PostmanNoGPU, exec, postman --disable-gpu

bind = CTRL ALT, left,  movecurrentworkspacetomonitor, l
bind = CTRL ALT, right, movecurrentworkspacetomonitor, r

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, D, Discord, exec, launch-or-focus-webapp Discord "https://discord.com/app"
bindd = SUPER, M, Music, exec, launch-or-focus-webapp Spotify "https://spotify.com"
bindd = SUPER, A, ChatGPT, exec, launch-or-focus-webapp ChatGPT "https://chatgpt.com"
bindd = SUPER, G, Github, exec, launch-or-focus-webapp GitHub "https://github.com/OmerBilgin21"
bindd = SUPER, C, Crunchyroll, exec, launch-or-focus-webapp Crunchyroll "https://www.crunchyroll.com/discover"
bindd = SUPER, Y, YouTube, exec, launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = ALT, W, WhatsApp, exec, launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER, N, Netflix, exec, launch-or-focus-webapp Netflix "https://www.netflix.com/browse"

unbind = SUPER, SPACE
bind = SUPER, SPACE, exec, pkill rofi || rofi -show drun
bind = SUPER SHIFT, E, exec, rofimoji --action=copy
bind = SUPER SHIFT, C, exec, rofi -show calc -modi "calc" -no-show-match -no-sort -calc-command "echo -n '{result}' | wl-copy"
bind = SUPER, o, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
