# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

monitor = eDP-1,1920x1080@144,auto,1.3333334

# 27 inch
monitor = ,2560x1440@59.95,auto,1.3333334
# fhd
# monitor = ,1920x1080@59.95,auto,1.20

# Optional fallback for unknown displays:
# monitor = ,preferred,auto,1.3333334

