---disable-gpu
--disable-gpu-compositing
--disable-accelerated-2d-canvas
--disable-accelerated-video-decode
--disable-accelerated-video-encode
--disable-gpu-rasterization
--disable-zero-copy
--disable-features=VaapiVideoDecoder,Vulkan-ozone-platform=wayland
--disable-features=Vulkan
--ozone-platform-hint=wayland
--enable-features=TouchpadOverscrollHistoryNavigation
--disable-background-networking
--disable-sync
--disable-background-timer-throttling
